### 2.1数据操作

#### 2.1.1 入门
创建张量
- 一个轴的张量对应数学上的一个响亮
- 两个轴的张量对应数学上的矩阵

In [1]:
import tensorflow as tf

In [2]:
X = tf.range(12)
X

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [3]:
X = tf.reshape(X, (3, 4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [4]:
#创建全0 全1 指定形状的张量
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [5]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [6]:
#创建一个均值为0 标准差为1的标准高斯正太分布
tf.random.normal(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.12069773,  1.2486733 ,  0.43239862,  0.2720299 ],
       [ 0.82293606, -1.109432  , -1.4389591 , -0.7415657 ],
       [-0.36817056, -0.30771548,  0.19274637,  0.9667155 ]],
      dtype=float32)>

In [7]:
x = tf.range(1, 5, dtype=float)
y = tf.ones(4) + 1
x + y, x - y, x ** y

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3., 4., 5., 6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  1.,  2.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4.,  9., 16.], dtype=float32)>)

连接 和numpy基本一致

In [8]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
print(X)
Y = tf.reshape(tf.range(88, 100, dtype=tf.float32), (3, 4))
print(Y)

tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[88. 89. 90. 91.]
 [92. 93. 94. 95.]
 [96. 97. 98. 99.]], shape=(3, 4), dtype=float32)


(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [88., 89., 90., 91.],
        [92., 93., 94., 95.],
        [96., 97., 98., 99.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3., 88., 89., 90., 91.],
        [ 4.,  5.,  6.,  7., 92., 93., 94., 95.],
        [ 8.,  9., 10., 11., 96., 97., 98., 99.]], dtype=float32)>)

进行布尔运算

In [9]:
X == Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [10]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

In [11]:
import numpy as np
X = np.arange(10)
Y = tf.constant(X)#实现numpy到tf的转换
Y

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [12]:
X = tf.range(12, dtype=tf.float32)
Y = X.numpy()#tf张量转化为numpy
Y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)

为多个元素赋相同的值
**tf中的tensors是不可变的，也不能被赋值。TF中的Variables是支持赋值的可变容器。但是TF中的梯度不会通过Variable反向传播**

In [13]:
X = tf.reshape(X, (3,4))
X_var = tf.Variable(X)
X_var[1, 2].assign(9)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [15]:
print(X_var.shape)

(3, 4)
