# 6 CNN

## 6.2 图像卷积


### 6.2.1 互相关运算
在卷积层中，输入张量和核张量通过互相关运算产生输出张量。
因为要足够的空间在图像上“移动卷积核，可以通过在图像边界周围填充0来保证有足够的空间移动内核。从而保持输出大小不变

In [2]:
import torch
from torch import nn
from d2l import torch as d2l

def corr2d(X, K):
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
    
    return Y
    

In [3]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
K = torch.tensor([[0.0, 1.0], [2.0, 3.0]])
corr2d(X, K)

tensor([[19., 25.],
        [37., 43.]])

### 6.2.2卷积层
基于上面定义的corr2d函数实现二维卷积层。在__init__构造函数中，将weight和bias声明为两个模型参数，前向传播函数调用corr2d函数并添加偏置

In [6]:
class Conv2D(nn.Module):
    def __init__(self, kernel_size):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(kernel_size))
        self.bias = nn.Parameter(torch.zeors(1))
        
    def forward(self, x):
        return corr2d(x, self.weight) + self.bias

### 6.2.3 图像中目标的边缘检测


In [8]:
X = torch.ones((6, 8))
X[:, 2: 6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

构造一个可以检测垂直边缘的卷积核

In [11]:
K = torch.Tensor([[1.0, -1.0]])
Y = corr2d(X, K)
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

对水平边缘的检测就不太行

In [12]:
corr2d(X.t(), K)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

### 6.2.4 学习卷积核


In [28]:
conv2d = nn.Conv2d(1, 1, kernel_size=(1, 2), bias=False)

#这个二维卷积层使用四维输入和输出格式（批量大小，通道，高度，宽度）
#其中批量大小和通道数都是1

X = X.reshape((1, 1, 6, 8))
Y = Y.reshape((1, 1, 6, 7))

for i in range(100):
    Y_hat = conv2d(X)
    l = (Y_hat - Y)  ** 2
    conv2d.zero_grad()
    l.sum().backward()
    conv2d.weight.data[:] -= 0.003 * conv2d.weight.grad
    print(f'batch {i+1}, loss {l.sum():.3f}')

batch 1, loss 18.863
batch 2, loss 17.485
batch 3, loss 16.219
batch 4, loss 15.052
batch 5, loss 13.974
batch 6, loss 12.977
batch 7, loss 12.053
batch 8, loss 11.197
batch 9, loss 10.402
batch 10, loss 9.665
batch 11, loss 8.980
batch 12, loss 8.345
batch 13, loss 7.754
batch 14, loss 7.205
batch 15, loss 6.696
batch 16, loss 6.222
batch 17, loss 5.782
batch 18, loss 5.373
batch 19, loss 4.993
batch 20, loss 4.640
batch 21, loss 4.312
batch 22, loss 4.007
batch 23, loss 3.724
batch 24, loss 3.461
batch 25, loss 3.216
batch 26, loss 2.989
batch 27, loss 2.777
batch 28, loss 2.581
batch 29, loss 2.398
batch 30, loss 2.229
batch 31, loss 2.071
batch 32, loss 1.925
batch 33, loss 1.789
batch 34, loss 1.662
batch 35, loss 1.545
batch 36, loss 1.435
batch 37, loss 1.334
batch 38, loss 1.240
batch 39, loss 1.152
batch 40, loss 1.071
batch 41, loss 0.995
batch 42, loss 0.925
batch 43, loss 0.859
batch 44, loss 0.798
batch 45, loss 0.742
batch 46, loss 0.689
batch 47, loss 0.641
batch 48, los

In [29]:
conv2d.weight.data.reshape((1, 2))

tensor([[ 0.9681, -0.9681]])

In [30]:
conv2d(X)

tensor([[[[ 0.0000,  0.9681,  0.0000,  0.0000,  0.0000, -0.9681,  0.0000],
          [ 0.0000,  0.9681,  0.0000,  0.0000,  0.0000, -0.9681,  0.0000],
          [ 0.0000,  0.9681,  0.0000,  0.0000,  0.0000, -0.9681,  0.0000],
          [ 0.0000,  0.9681,  0.0000,  0.0000,  0.0000, -0.9681,  0.0000],
          [ 0.0000,  0.9681,  0.0000,  0.0000,  0.0000, -0.9681,  0.0000],
          [ 0.0000,  0.9681,  0.0000,  0.0000,  0.0000, -0.9681,  0.0000]]]],
       grad_fn=<ThnnConv2DBackward>)

## 6.3 填充和步幅
- 填充可以解决输入和输出大小不一致的问题
- 步幅可以解决输入的分辨率冗余的问题

### 6.3.1 填充
一般卷积核大小kxk都是奇数，这样可以：
- 所有边的填充行数(k - 1) / 2 都相同
- 输入和输出具有相同的高度和宽度

In [6]:
import torch
from torch import nn

#这个函数初始化卷积层权重，对输入和输入提高和缩减相应的维数
def comp_conv2d(conv2d, X):
    #这里的(1, 1)表示批量大小和通道数都是1
    X = X.reshape((1, 1) + X.shape)
    Y = conv2d(X)
    #省略前两个维度：批量大小和通道
    return Y.reshape(Y.shape[2:])

conv2d = nn.Conv2d(1, 1 ,kernel_size=3, padding=1)
X = torch.rand(size=(8, 8))
comp_conv2d(conv2d, X).shape

torch.Size([8, 8])

当卷积内核的高度和宽度不同的时候，可以填充不同的高度、宽度，让输入输出的size相同

In [8]:
conv2d = nn.Conv2d(1, 1, kernel_size=(5, 3), padding=(2, 1))
comp_conv2d(conv2d, X).shape

torch.Size([8, 8])

### 6.3.2 步幅
之前默认每次卷积都滑动1个窗口，为了减小输出的冗余，可以设置水平、竖直步幅。
注意如果数据大小不足以让卷积核继续按照步幅滑动，则不计算剩下的数据。即计算输出大小的时候是向下取整

将高度和宽度的步幅设置为2，从而将输入的高度和宽度减半

In [11]:
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=2)
comp_conv2d(conv2d, X).shape

torch.Size([4, 4])

In [12]:
conv2d = nn.Conv2d(1, 1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))
comp_conv2d(conv2d, X).shape

torch.Size([2, 2])

## 6.4 多输入多输出通道
每个RGB图像具有3 x h x W的形状。这个大小为3的轴被称为通道（channel）维度

### 6.4.1 多输入通道
如果输入包含多个通道，需要构造一个与输入数据具有相同输入通道数目的卷积核，以便与输入数据进行互相关运算。
输出的结果是每个通道对应位置之和

In [66]:
import torch

#这里匿名函数传入三个参数，x，可变参数*args 作为tuple传进， **kwargs作为dict传入，这里后面两个参数没啥用
reduce_sum = lambda x, *args, **kwargs: x.sum(*args, **kwargs)

def corr2d(X, K):
    #计算二维互相关运算
    #print(X.shape, K.shape)
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = reduce_sum(X[i:i+h, j:j+w] * K)
            #print(X[i:i+h, j:j+w] * K)  
    return Y

def corr2d_multi_in(X, K):
    # 先遍历 “X” 和 “K” 的第0个维度（通道维度），再把它们加在一起
    return sum(corr2d(x, k) for x, k in zip(X, K))

In [75]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

corr2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

### 6.4.2 多输出通道
随着神经网络层数的增加，经常会增加输出通道的维数。可以将每个通道看做是对不同特征的相应，但是实际上每个通道不是独立的，是为了共同使用而优化的

计算一个多通道的互相关函数

In [76]:
#stack 是沿着一个新的维度对输入张量序列进行连接。序列中的所有张量都应该是相同的形状
x1 = torch.arange(4).reshape(2, 2)
x2 = torch.arange(4, 8).reshape(2, 2)
torch.stack([x1, x2], 0)

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [77]:
def corr2d_multi_in_out(X, K):
    # 迭代“K”的第0个维度，每次都对输入“X”执行互相关运算。
    # 最后将所有结果都叠加在一起
    return torch.stack([corr2d_multi_in(X, k) for k in K], 0)

构造一个有三个通道的卷积核

In [78]:
K = torch.stack((K, K + 1, K + 2), dim=0)
K.shape

torch.Size([3, 2, 2, 2])

In [79]:
corr2d_multi_in_out(X, K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])